version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.100'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "192.168.1.100"
        gitlab_rails['registry_port'] = "5050"
        registry_external_url 'http://192.168.1.100:5050'
    ports:
      - "80:80"     # Expose HTTP on port 80
      - "443:443"   # Expose HTTPS on port 443
      - "5050:5050" # Expose GitLab Container Registry on port 5050
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/registry:/var/opt/gitlab/gitlab-rails/shared/registry # Add a volume for registry data



#To put password to gitlab
#sudo docker exec -it gitlab gitlab-rake "gitlab:password:reset[root]"

#./gitlab/config:/etc/gitlab: It's used to persist GitLab configuration files.
#./gitlab/logs:/var/log/gitlab: It's used to persist GitLab log files.
#./gitlab/data:/var/opt/gitlab: It's used to persist GitLab data,including repositories,databases,and other runtime data.